In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4506, 5757, 5291, 696],
 [4506, 5757, 5291, 3267],
 [4506, 4747, 5291, 5954],
 [9109, 4207, 1769, 3977, 7364],
 [9109, 4207, 1769, 3977, 6626],
 [3449, 4506, 8149, 5291, 420],
 [2888, 6194, 6595, 3977]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4506 5757 5291  696]
 [   0    0    0    0 4506 5757 5291 3267]
 [   0    0    0    0 4506 4747 5291 5954]
 [   0    0    0 9109 4207 1769 3977 7364]
 [   0    0    0 9109 4207 1769 3977 6626]
 [   0    0    0 3449 4506 8149 5291  420]
 [   0    0    0    0 2888 6194 6595 3977]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 231ms/step


array([[[ 0.03640095,  0.00850481,  0.04281025,  0.02381003,
         -0.00799099, -0.02259741,  0.00778747,  0.04193475,
          0.02721579,  0.01294006],
        [ 0.03640095,  0.00850481,  0.04281025,  0.02381003,
         -0.00799099, -0.02259741,  0.00778747,  0.04193475,
          0.02721579,  0.01294006],
        [ 0.03640095,  0.00850481,  0.04281025,  0.02381003,
         -0.00799099, -0.02259741,  0.00778747,  0.04193475,
          0.02721579,  0.01294006],
        [ 0.03640095,  0.00850481,  0.04281025,  0.02381003,
         -0.00799099, -0.02259741,  0.00778747,  0.04193475,
          0.02721579,  0.01294006],
        [-0.03223614,  0.04939239, -0.03302701, -0.02039265,
         -0.02176801,  0.01773057, -0.04300323,  0.00519987,
         -0.01175674,  0.04872966],
        [-0.00183384, -0.00667164, -0.01853172, -0.01582599,
         -0.0243537 , -0.00902393, -0.03468024, -0.00648682,
         -0.03285377,  0.03134802],
        [ 0.02285865,  0.04785513,  0.04205358, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4506, 5757, 5291,  696])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[ 0.03640095,  0.00850481,  0.04281025,  0.02381003, -0.00799099,
        -0.02259741,  0.00778747,  0.04193475,  0.02721579,  0.01294006],
       [ 0.03640095,  0.00850481,  0.04281025,  0.02381003, -0.00799099,
        -0.02259741,  0.00778747,  0.04193475,  0.02721579,  0.01294006],
       [ 0.03640095,  0.00850481,  0.04281025,  0.02381003, -0.00799099,
        -0.02259741,  0.00778747,  0.04193475,  0.02721579,  0.01294006],
       [ 0.03640095,  0.00850481,  0.04281025,  0.02381003, -0.00799099,
        -0.02259741,  0.00778747,  0.04193475,  0.02721579,  0.01294006],
       [-0.03223614,  0.04939239, -0.03302701, -0.02039265, -0.02176801,
         0.01773057, -0.04300323,  0.00519987, -0.01175674,  0.04872966],
       [-0.00183384, -0.00667164, -0.01853172, -0.01582599, -0.0243537 ,
        -0.00902393, -0.03468024, -0.00648682, -0.03285377,  0.03134802],
       [ 0.02285865,  0.04785513,  0.04205358, -0.01975387, -0.04072894,
        -0.01502638,  0.00792571,  0.01249371